name: Deploy Discord Bot

on:
  push:
    branches:
      - main  # Ganti dengan branch yang Anda gunakan, misalnya 'main' atau 'master'
  pull_request:
    branches:
      - main  # Ganti dengan branch yang Anda gunakan

jobs:
  build:
    runs-on: ubuntu-latest  # Pilih runner Ubuntu

    steps:
      # 1. Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Versi Python yang Anda gunakan, misalnya '3.12'

      # 3. Install dependencies required for building
      - name: Install dependencies for building
        run: |
          sudo apt update
          sudo apt install -y python3-dev python3-venv build-essential

      # 4. Create and activate virtual environment
      - name: Create and activate virtual environment
        run: |
          python3 -m venv venv  # Membuat virtual environment
          . venv/bin/activate  # Mengaktifkan virtual environment

      # 5. Upgrade pip and install dependencies from requirements.txt
      - name: Install dependencies from requirements.txt
        run: |
          . venv/bin/activate  # Pastikan venv sudah aktif
          pip install --upgrade pip  # Memperbarui pip ke versi terbaru
          pip install -r requirements.txt  # Menginstal dependencies

      # 6. Run linting with flake8
      - name: Run flake8 for linting
        run: |
          . venv/bin/activate  # Pastikan venv sudah aktif
          pip install flake8  # Menginstal flake8 untuk linting
          flake8 .  # Memeriksa kualitas kode dengan flake8

      # 7. Run tests with pytest (optional step)
      - name: Run tests with pytest
        run: |
          . venv/bin/activate  # Pastikan venv sudah aktif
          pip install pytest  # Menginstal pytest untuk testing
          pytest  # Menjalankan pengujian jika ada file test

      # 8. Run Discord bot
      - name: Run Discord Bot
        run: |
          . venv/bin/activate  # Pastikan venv sudah aktif
          python KRS-app.py  # Ganti dengan file utama bot Anda jika perlu

      # 9. Send a notification (optional step, can be a Slack message, etc.)
      - name: Send notification
        run: |
          # Contoh mengirimkan notifikasi via Slack menggunakan webhook
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"Discord bot has been deployed successfully!"}' \
          https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX
